routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/hotnews', 'HomeController@hotnewsIndex')->name('home.hotnews.index');
Route::get('/berita-terbaru', 'HomeController@beritaBaruIndex')->name('home.beritaTerbaru.index');
Route::get('/highlight', 'HomeController@highlightIndex')->name('home.highlight.index');
Route::get('/galleries', 'HomeController@galleries')->name('home.galleries.index');
Route::get('/hotnews/{content}', 'ContentController@show')->name('content.hotnews.show');
Route::get('/berita-terbaru/{content}', 'ContentController@show')->name('content.beritaTerbaru.show');
Route::get('/highlight/{content}', 'ContentController@show')->name('content.highlight.show');
/* ADMIN PANEL */
Route::get('admin/login', 'AdminController@login')->name('login');
Route::post('admin/login','AdminController@auth_login');

Route::name('admin.')->prefix('admin')->middleware('auth')->group(function () {
    Route::get('/', 'AdminController@index');
    Route::resource('/contents', 'ContentController');
    Route::get('/galleries', 'GalleriesController@index')->name('galleries.index');
    Route::post('/galleries', 'GalleriesController@store')->name('galleries.store');
    Route::post('/images', 'GalleriesController@upload')->name('UploadImage');
    Route::resource('/slider-images', 'SliderImagesController');
    Route::put('/mass-update/slider-images', 'SliderImagesController@massUpdate')->name('slider-images.massUpdate');
});

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    /** TYPES
     * carousel => should hyperlinked to article
     * content_image => inside article
     * bg_content_thumbnail => article
     * sm_content_thumbnail => article
     * cube_image => latest (4 items)
     * galleries => latest (4 items)
     */
    protected $fillable = [
        'type', 'url', 'active'
    ];
}

app/Http/Controllers/GalleriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Gallery;

class GalleriesController extends Controller
{
    public function index()
    {
        $galleries = Gallery::where('type', 'galleries')->paginate(12);

        return view('admin.galleries.index', compact('galleries'));
    }
    
    public function upload(Request $request)
    {
        $file = $request->file('image');
        $name = $file->getClientOriginalName();
        $name = explode('.', $name);
        $name = time() . '_' . strtolower($name[0]) . '.' . $file->getClientOriginalExtension();
        $file->move(public_path('uploads/contents'), $name);
        $image = Gallery::create([
            'type' => $request->input('type'),
            'url' => url('uploads/contents/'. $name)
        ]);
        return $image->url;
    }

    public function store(Request $request)
    {
        $file = $request->file('image');
        $name = $file->getClientOriginalName();
        $name = explode('.', $name);
        $name = time() . '_' . strtolower($name[0]) . '.' . $file->getClientOriginalExtension();
        $file->move(public_path('uploads/galleries'), $name);
        $image = Gallery::create([
            'type' => $request->input('type'),
            'url' => url('uploads/galleries/'. $name)
        ]);
        return redirect()->route('admin.galleries.index');
    }
}

resources/views/admin/galleries/partials/add-new-image-modal.blade.php
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <form action="{{route('admin.galleries.store')}}" method="POST" enctype="multipart/form-data">
    {{csrf_field()}}    
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="type" value="galleries">
                    <input type="file" name="image" id="">
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <input type="submit" class="btn btn-primary" value="Save changes">
            </div>
            </div>
        </div>
    </form>
</div>