routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/hotnews', 'HomeController@hotnewsIndex')->name('home.hotnews.index');
Route::get('/berita-terbaru', 'HomeController@beritaBaruIndex')->name('home.beritaTerbaru.index');
Route::get('/highlight', 'HomeController@highlightIndex')->name('home.highlight.index');
Route::get('/galleries', 'HomeController@galleries')->name('home.galleries.index');
Route::get('/hotnews/{content}', 'ContentController@show')->name('content.hotnews.show');
Route::get('/berita-terbaru/{content}', 'ContentController@show')->name('content.beritaTerbaru.show');
Route::get('/highlight/{content}', 'ContentController@show')->name('content.highlight.show');
/* ADMIN PANEL */
Route::get('admin/login', 'AdminController@login')->name('login');
Route::post('admin/login','AdminController@auth_login');

Route::name('admin.')->prefix('admin')->middleware('auth')->group(function () {
    Route::get('/', 'AdminController@index');
    Route::resource('/contents', 'ContentController');
    Route::get('/galleries', 'GalleriesController@index')->name('galleries.index');
    Route::post('/galleries', 'GalleriesController@store')->name('galleries.store');
    Route::post('/images', 'GalleriesController@upload')->name('UploadImage');
    Route::resource('/slider-images', 'SliderImagesController');
    Route::put('/mass-update/slider-images', 'SliderImagesController@massUpdate')->name('slider-images.massUpdate');
});

resources/views/admin/sliders/index.blade.php
@extends('layouts.base-admin')
@section('title', 'Admin Panel')

@section('style')
<style>
    .checked-images {
        padding: 15px;
        border: 3px solid #007bff;
        border-radius: 2px;
    }
    .going-active-img {
        padding: 15px;
        border: 3px solid #007bff;
        border-radius: 2px;
    }
    .deactive-btn {
        display: none;
        margin: 15px;
    }
    .active-btn {
        display: none;
        margin: 15px;
    }
</style>
@endsection

@section('body')
<div id="gmo-admin-home" style="min-height: 700px;">
    <div id="gmo-admin-content" style="margin-bottom: 30px;">
        <h3 style="border-bottom: 3px solid black; padding-bottom: 15px">SLIDER IMAGES
            <span style="float: right; font-size: 14px;">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    ADD NEW IMAGES
                </button>
            </span>
        </h3>
        <div>
            <p>IMAGES THAT USED IN SLIDERS</p>
            <div>
            @foreach($activeImages->chunk(3) as $chunkedImages)
            <div class="row">
                @foreach($chunkedImages as $img)
                    <input style="display: none" type="checkbox" class="image-id-checkbox" name="imageIds[]" id="image-id-{{$img->id}}" value="{{$img->id}}">
                    <div class="col-md-4 active-images" data-image-id="{{$img->id}}" style="padding: 15px;">
                        <img src="{{$img->url}}" style="width: 100%;" alt="">
                    </div>
                @endforeach
            </div>
            @endforeach
            <button type="button" class="btn btn-danger deactive-btn">
                DEACTIVATE THIS IMAGES
            </button>
            </div>
        </div>

        <div style="border-top: 1px solid; padding: 15px 0;">
            <p>REMAINING IMAGES</p>
            <div>
                @foreach($inactiveImages->chunk(3) as $chunkedImages)
                <div class="row">
                    @foreach($chunkedImages as $img)
                        <div class="col-md-4 inactive-images" data-image-id="{{$img->id}}" style="padding: 15px;">
                            <img src="{{$img->url}}" style="width: 100%" alt="">
                        </div>
                    @endforeach
                </div>
                @endforeach
                <button type="button" class="btn btn-primary active-btn">
                    ACTIVATE THIS IMAGES
                </button>
            </div>
        </div>

        <!-- MODAL -->
        @include('admin.sliders.partials.newImagesModal')
    </div>
</div>
@endsection

@section('script')
<script>
    var token = "{{ csrf_token() }}"
    $('.active-images').on('click', function() {
        $(this).toggleClass('checked-images');
        var imgId = $(this).data('image-id');
        $(this).hasClass('checked-images')
        var checkedImages = $('.checked-images');
        if (checkedImages.length > 0) {
            $('.deactive-btn').show();
        } else {
            $('.deactive-btn').hide();            
        }
    })
    
    /** CHANGE THIS TO UPDATE THE IMAGES SLIDER */
    $('.deactive-btn').on('click', function() {
        var checkedImages = $('.checked-images'); 
        var ids = []       
        checkedImages.each(function() {
            ids.push($(this).data('image-id'))
        })

        var data = {
            _token: token,
            ids: ids
        }

        $.ajax({
            url: "{{route('admin.slider-images.massUpdate')}}",
            data: data,
            type: "put",
            success: function(response) {
                alert("GAMBAR SUDAH TIDAK DIJADIKAN SLIDE")
                location.reload()
            },
            error: function(data) {
                alert("BILANG KE DEVELOPER ADA ERROR!")
            }
        });
    })

    $('.inactive-images').on('click', function() {
        $(this).toggleClass('going-active-img');
        var imgId = $(this).data('image-id');
        $(this).hasClass('going-active-img')
        var checkedImages = $('.going-active-img');
        if (checkedImages.length > 0) {
            $('.active-btn').show();
        } else {
            $('.active-btn').hide();            
        }
    })

    $('.active-btn').on('click', function() {
        var checkedImages = $('.going-active-img'); 
        var ids = []
        checkedImages.each(function() {
            ids.push($(this).data('image-id'))
            console.log(ids)
        })
        var data = {
            _token: token,
            ids: ids,
            activate: true
        }
        
        $.ajax({
            url: "{{route('admin.slider-images.massUpdate')}}",
            data: data,
            type: "put",
            success: function(response) {
                alert("GAMBAR SUDAH DIJADIKAN SLIDE")
                location.reload()
            },
            error: function(data) {
                alert("BILANG KE DEVELOPER ADA ERROR!")
            }
        });
    })
</script>
@endsection