routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/hotnews', 'HomeController@hotnewsIndex')->name('home.hotnews.index');
Route::get('/berita-terbaru', 'HomeController@beritaBaruIndex')->name('home.beritaTerbaru.index');
Route::get('/highlight', 'HomeController@highlightIndex')->name('home.highlight.index');
Route::get('/galleries', 'HomeController@galleries')->name('home.galleries.index');
Route::get('/hotnews/{content}', 'ContentController@show')->name('content.hotnews.show');
Route::get('/berita-terbaru/{content}', 'ContentController@show')->name('content.beritaTerbaru.show');
Route::get('/highlight/{content}', 'ContentController@show')->name('content.highlight.show');
/* ADMIN PANEL */
Route::get('admin/login', 'AdminController@login')->name('login');
Route::post('admin/login','AdminController@auth_login');

Route::name('admin.')->prefix('admin')->middleware('auth')->group(function () {
    Route::get('/', 'AdminController@index');
    Route::resource('/contents', 'ContentController');
    Route::get('/galleries', 'GalleriesController@index')->name('galleries.index');
    Route::post('/galleries', 'GalleriesController@store')->name('galleries.store');
    Route::post('/images', 'GalleriesController@upload')->name('UploadImage');
    Route::resource('/slider-images', 'SliderImagesController');
    Route::put('/mass-update/slider-images', 'SliderImagesController@massUpdate')->name('slider-images.massUpdate');
});

app/Content.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Content extends Model
{
    /** tag_id info
     * 1 = highlight
     * 2 = berita_terbaru
     * 3 = hot_news
     */

    use SoftDeletes;

    protected $fillable = [
        'title',
        'meta_title',
        'sm_thumb_image',
        'bg_thumb_image',
        'description',
        'tag_id',
        'content',
        'views',
        'published_at'
    ];

    protected $dates = [
        'published_at',
        'deleted_at'
    ];

    public function tag()
    {
        return $this->belongsTo(Tag::class, 'tag_id');
    }

    public function plusView()
    {
        $this->views += 1;
        $this->save();
    }
}

app/Http/Controllers/ContentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Content;
use App\Tag;
use Carbon\Carbon;

class ContentController extends Controller
{
    public function index(Request $request)
    {
        $contents = Content::with('tag')->paginate(10);
        return view('admin.contents.index', compact('contents'));
    }

    public function show(Request $request, $content)
    {
        $showedContent = Content::where('meta_title', $content)->first();
        $title = $showedContent->title;
        return view('home.contents.show', compact('showedContent', 'title'));
    }

    public function create()
    {
        $tags = Tag::all();
        return view('admin.contents.create', compact('tags'));
    }

    public function store(Request $request)
    {
        $data = $request->except('_token');
        $data['meta_title'] = time() . '-' . str_replace(' ', '-', $request->title);
        if ($request->has('publish')) {
            $data['published_at'] = Carbon::now();
        }

        $content = Content::create($data);
        $content->meta_title = $content->created_at->format('dmYhis') . '-' . str_replace(' ', '-', $content->title);
        $content->save();
        return response()->json([
            'success' => 'true',
            'message' => 'article created successfully'
        ]);
    }

    public function edit($id)
    {
        $content = Content::find($id);
        $tags = Tag::all();
        return view('admin.contents.edit', compact('content', 'tags'));
    }

    public function update(Request $request, $id)
    {
        $content = Content::find($id);
        $data = $request->except('_token');
        $meta_title = preg_replace('/[?]/', '', $request->title);
        $data['meta_title'] = $content->created_at->format('dmYhis') . '-' . str_replace(' ', '-', $meta_title);
        if ($request->has('publish')) {
            $data['published_at'] = Carbon::now();
        } elseif ($request->has('unpublish')) {
            $data['published_at'] = null;
        }

        $new_content = $content->update($data);

        return response()->json([
            'success' => 'true',
            'message' => 'article updated successfully'
        ]);
    }
}

resources/views/admin/contents/create.blade.php
@extends('layouts.base-admin')
@section('title', 'Admin Panel')

@section('body')
<div id="gmo-admin-home" style="min-height: 700px;">
    <div id="gmo-admin-content" style="margin-bottom: 30px;">
        <h3 style="border-bottom: 3px solid black; padding-bottom: 5px">CREATE NEW CONTENT</h3>
        <div class="form-group">
            <select class="form-control form-control-sm" id="tag-select">
                <option disabled selected>Select Categories...</option>
                @foreach($tags as $tag)
                    <option value="{{$tag->id}}">{{ucfirst(str_replace('_', ' ', $tag->name))}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" required id="title" placeholder="Enter Title*">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" rows="3"></textarea>
        </div>
        <label for="summernote">Content</label>
        <div id="summernote"></div>
        <br>
        <div class="form-group">
            <label for="bg-thumbnail">Add Big Thumbnail Image*</label>
            <input type="file" name="file" id="bg-thumbnail" class="form-control-file">
            <input type="hidden" id="bg-thumb-link">
            <div class="row">
                <div class="col-md-4">
                    <img style="width: 100%" src="" id="bg-thumb-preview" alt="">
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="sm-thumbnail">Add Small Thumbnail Image (for mobile)*</label>
            <input type="file" name="file" id="sm-thumbnail" class="form-control-file">
            <input type="hidden" id="sm-thumb-link">
            <div class="row">
                <div class="col-md-2">
                    <img style="width: 100%" src="" id="sm-thumb-preview" alt="">
                </div>
            </div>
        </div>
    </div>

    <button id="save_draft" class="btn btn-success">
        save as draft
    </button>
    or
    <button id="save_publish" class="btn btn-success">
        save and publish
    </button>
</div>
@endsection

@section('script')
<script>
    $('#summernote').summernote({
        placeholder: 'Write Your Content Here',
        tabsize: 2,
        height: 300,
        callbacks: {
            onImageUpload: function(image) {
                uploadImage(image[0]);
            }
        }
    });

    $('#bg-thumbnail').on('change', function() {
        var file = $(this)[0].files[0];
        uploadFile($(this)[0].files[0], 'bg_content_thumbnail').then(function(url) {
            $('#bg-thumb-link').val(url)
            $('#bg-thumb-preview').attr('src', url)
        });
    });

    $('#sm-thumbnail').on('change', function() {
        var file = $(this)[0].files[0];
        uploadFile($(this)[0].files[0], 'sm_content_thumbnail').then(function(url) {
            $('#sm-thumb-link').val(url)
            $('#sm-thumb-preview').attr('src', url)
        });
    });

    function uploadImage(img) {
        var data = new FormData();
            data.append('_token', "{{csrf_token()}}")
            data.append("image", img);
            data.append('type', 'content_image')
            $.ajax({
                url: "{{route('admin.UploadImage')}}",
                cache: false,
                contentType: false,
                processData: false,
                data: data,
                type: "post",
                success: function(url) {
                    var image = $('<img>').attr('src', url);
                    $('#summernote').summernote("insertNode", image[0]);
                },
                error: function(data) {
                    console.log(data);
                }
            });
    }
    /** UPLOAD FILE FUNCTION FOR ALL */
    function uploadFile(file, type) {
        var data = new FormData();
        data.append('_token', "{{csrf_token()}}")
        data.append("image", file);
        data.append('type', type)
        return Promise.resolve(
            $.ajax({
                url: "{{route('admin.UploadImage')}}",
                cache: false,
                contentType: false,
                processData: false,
                data: data,
                type: "post",
                success: function(url) {
                    return url;
                },
                error: function(data) {
                    console.log(data);
                }
            })
        )
    }
    $('#save_draft').on('click', function() {
        var markupStr = $('#summernote').summernote('code');
        var tag_id = $('#tag-select').val();
        var data = {
            _token: "{{csrf_token()}}",
            title: $('#title').val(),
            description: $('#description').val(),
            tag_id: tag_id,
            sm_thumb_image: $('#sm-thumb-link').val(),
            bg_thumb_image: $('#bg-thumb-link').val(),
            content: markupStr
        }
        $.ajax({
            url: "{{route('admin.contents.store')}}",
            data: data,
            type: "post",
            success: function(response) {
                alert("CONTENT SUDAH DI SIMPAN DI DRAFT BOSQUE")
            },
            error: function(data) {
                alert("BILANG KE DEVELOPER ADA ERROR!")
            }
        });
    })

    $('#save_publish').on('click', function() {
        var markupStr = $('#summernote').summernote('code');
        var tag_id = $('#tag-select').val();
        var data = {
            _token: "{{csrf_token()}}",
            title: $('#title').val(),
            description: $('#description').val(),
            tag_id: tag_id,
            content: markupStr,
            sm_thumb_image: $('#sm-thumb-link').val(),
            bg_thumb_image: $('#bg-thumb-link').val(),
            publish: true
        }
        $.ajax({
            url: "{{route('admin.contents.store')}}",
            data: data,
            type: "post",
            success: function(response) {
                alert("CONTENT SUDAH DI PUBLISH BOSQUE")
            },
            error: function(data) {
                alert("BILANG KE DEVELOPER ADA ERROR!")
            }
        });
    })

</script>
@endsection

resources/views/admin/contents/edit.blade.php
@extends('layouts.base-admin')
@section('title', 'Admin Panel')

@section('body')
<div id="gmo-admin-home" style="min-height: 700px;">
    <div id="gmo-admin-content" style="margin-bottom: 30px;">
        <h3 style="border-bottom: 3px solid black; padding-bottom: 5px">CREATE NEW CONTENT</h3>
        <div class="form-group">
            <select class="form-control form-control-sm" id="tag-select">
                @foreach($tags as $tag)
                    <option value="{{$tag->id}}" {{$tag->id == $content->tag_id ? 'selected' : ''}}>{{ucfirst(str_replace('_', ' ', $tag->name))}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <input type="text" class="form-control" value="{{$content->title}}" required id="title" placeholder="Enter Title*">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" rows="3">{{$content->description}}</textarea>
        </div>
        <div id="summernote">
            {!! $content->content !!}
        </div>

        <br>
        <div class="form-group">
            <label for="bg-thumbnail">Add Big Thumbnail Image*</label>
            <input type="file" name="file" id="bg-thumbnail" class="form-control-file">
            <input type="hidden" value="{{$content->bg_thumb_image}}" id="bg-thumb-link">
            <div class="row">
                <div class="col-md-4">
                    <img style="width: 100%" src="{{$content->bg_thumb_image}}" id="bg-thumb-preview" alt="">
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="sm-thumbnail">Add Small Thumbnail Image (for mobile)*</label>
            <input type="file" name="file" id="sm-thumbnail" class="form-control-file">
            <input type="hidden" value="{{$content->sm_thumb_image}}" id="sm-thumb-link">
            <div class="row">
                <div class="col-md-2">
                    <img style="width: 100%" src="{{$content->sm_thumb_image}}" id="sm-thumb-preview" alt="">
                </div>
            </div>
        </div>
    </div>

    <button id="save" class="btn btn-success">
        save
    </button>
    or
    <button id="save_publish" class="btn btn-success">
        save and publish
    </button>
</div>
@endsection

@section('script')
<script>
    $('#summernote').summernote({
        focus: true,        
        tabsize: 2,
        height: 300,
        callbacks: {
            onImageUpload: function(image) {
                uploadImage(image[0]);
            }
        }
    });

    $('#bg-thumbnail').on('change', function() {
        var file = $(this)[0].files[0];
        uploadFile($(this)[0].files[0], 'bg_content_thumbnail').then(function(url) {
            $('#bg-thumb-link').val(url)
            $('#bg-thumb-preview').attr('src', url)
        });
    });

    $('#sm-thumbnail').on('change', function() {
        var file = $(this)[0].files[0];
        uploadFile($(this)[0].files[0], 'sm_content_thumbnail').then(function(url) {
            $('#sm-thumb-link').val(url)
            $('#sm-thumb-preview').attr('src', url)
        });
    });

    /** UPLOAD FILE FUNCTION FOR ALL */
    function uploadFile(file, type) {
        var data = new FormData();
        data.append('_token', "{{csrf_token()}}")
        data.append("image", file);
        data.append('type', type)
        return Promise.resolve(
            $.ajax({
                url: "{{route('admin.UploadImage')}}",
                cache: false,
                contentType: false,
                processData: false,
                data: data,
                type: "post",
                success: function(url) {
                    return url;
                },
                error: function(data) {
                    console.log(data);
                }
            })
        )
    }

    function uploadImage(img) {
        var data = new FormData();
            data.append('_token', "{{csrf_token()}}")
            data.append("image", img);
            data.append('type', 'content_image')
            $.ajax({
                url: "{{route('admin.UploadImage')}}",
                cache: false,
                contentType: false,
                processData: false,
                data: data,
                type: "post",
                success: function(url) {
                    var image = $('<img>').attr('src', url);
                    $('#summernote').summernote("insertNode", image[0]);
                },
                error: function(data) {
                    console.log(data);
                }
            });
    }
    
    $('#save').on('click', function() {
        var markupStr = $('#summernote').summernote('code');
        var tag_id = $('#tag-select').val();
        var data = {
            _token: "{{csrf_token()}}",
            title: $('#title').val(),
            description: $('#description').val(),
            tag_id: tag_id,
            sm_thumb_image: $('#sm-thumb-link').val(),
            bg_thumb_image: $('#bg-thumb-link').val(),
            content: markupStr
        }
        $.ajax({
            url: "{{route('admin.contents.update', ['content' => $content->id])}}",
            data: data,
            type: "put",
            success: function(response) {
                alert("CONTENT SUDAH DI SIMPAN DI DRAFT BOSQUE")
                location.reload()
            },
            error: function(data) {
                alert("BILANG KE DEVELOPER ADA ERROR!")
                location.reload()
            }
        });
    })

    $('#save_publish').on('click', function() {
        var markupStr = $('#summernote').summernote('code');
        var tag_id = $('#tag-select').val();
        var data = {
            _token: "{{csrf_token()}}",
            title: $('#title').val(),
            description: $('#description').val(),
            tag_id: tag_id,
            content: markupStr,
            sm_thumb_image: $('#sm-thumb-link').val(),
            bg_thumb_image: $('#bg-thumb-link').val(),
            publish: true
        }
        $.ajax({
            url: "{{route('admin.contents.update', ['content' => $content->id])}}",
            data: data,
            type: "put",
            success: function(response) {
                alert("CONTENT SUDAH DI PUBLISH BOSQUE")
                location.reload()
            },
            error: function(data) {
                alert("BILANG KE DEVELOPER ADA ERROR!")
                location.reload()
            }
        });
    })

</script>
@endsection

resources/views/admin/contents/index.blade.php
@extends('layouts.base-admin')
@section('title', 'Admin Panel')

@section('body')
<div id="gmo-admin-home" style="min-height: 700px;">
    <div id="gmo-admin-content" style="margin-bottom: 30px;">
        <h3 style="border-bottom: 3px solid black; padding-bottom: 5px">CONTENT LIST
            <span style="float: right; font-size: 14px; margin-top: 10px"><a class="gmo-link-inverse" href="{{route('admin.contents.create')}}">Create New</a></span>
        </h3>
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                <th scope="col">Id</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Category</th>
                <th scope="col">Views</th>
                <th scope="col">Published At</th>
                <th scope="col">Created At</th>
                <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($contents as $content)
                <tr>
                    <th scope="row">{{$content->id}}</th>
                    <td>{{$content->title}}</td>
                    <td>{{$content->description}}</td>
                    <td>{{ucfirst(str_replace('_', ' ', $content->tag->name))}}</td>
                    <td>{{$content->views}}</td>
                    <td>{{$content->published_at ? $content->published_at->format('d-m-Y h:i:s A') : 'not published yet'}}</td>
                    <td>{{$content->created_at->format('d-m-Y')}}</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Action
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{{route('admin.contents.show', ['metaTitle' => $content->meta_title])}}">Preview</a>
                                <a class="dropdown-item" href="{{route('admin.contents.edit', ['id' => $content->id])}}">Edit</a>
                                <a class="content-publish dropdown-item" href="#" data-id="{{$content->id}}" data-published="{{$content->published_at ? 'true' : 'false'}}">{{$content->published_at ? 'Unpublish' : 'Publish'}}</a>
                            </div>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{$contents->links()}}
    </div>
</div>
@endsection

@section('script')
<script>
    $('.content-publish').on('click', function() {   
        var published = $(this).data('published')    
        var contentId = $(this).data('id')
        var data = {
            _token: "{{csrf_token()}}"
        }
        /** SET DATA PUBLISHED OR UNPUBLISH */
        if (published) {
            data.unpublish = true;           
        } else {
            data.publish = true;
        }

        $.ajax({
            url: "{{route('admin.contents.update', ['content' => ':id'])}}".replace(":id", contentId),
            data: data,
            type: "put",
            success: function(response) {
                alert("CONTENT SUDAH DI UPDATE BOSQUE")
                location.reload()
            },
            error: function(data) {
                alert("ADA ERROR BOSQUE")
                location.reload()                
            }
        });
    })
</script>
@endsection